/* Generated by Yosys 0.54 (git sha1 db72ec3bde296a9512b2d1e6fabf81cfb07c2c1b, clang++ 19.1.7 -fPIC -O3) */

(* top =  1  *)
(* src = "mem2048x32.sv:6.1-137.10" *)
module mem_ctrl_2048x32(clk_i, rst_ni, mem_valid_i, mem_instr_i, mem_addr_i, mem_wdata_i, mem_wstrb_i, mem_rdata_o, mem_ready_o);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  (* src = "mem512x32.sv:50.9-50.28" *)
  wire _04_;
  (* src = "mem512x32.sv:62.9-62.28" *)
  wire _05_;
  (* src = "mem512x32.sv:74.9-74.28" *)
  wire _06_;
  (* src = "mem512x32.sv:87.9-87.28" *)
  wire _07_;
  (* src = "mem512x32.sv:50.9-50.28" *)
  wire _08_;
  (* src = "mem512x32.sv:62.9-62.28" *)
  wire _09_;
  (* src = "mem512x32.sv:74.9-74.28" *)
  wire _10_;
  (* src = "mem512x32.sv:87.9-87.28" *)
  wire _11_;
  (* src = "mem512x32.sv:50.9-50.28" *)
  wire _12_;
  (* src = "mem512x32.sv:62.9-62.28" *)
  wire _13_;
  (* src = "mem512x32.sv:74.9-74.28" *)
  wire _14_;
  (* src = "mem512x32.sv:87.9-87.28" *)
  wire _15_;
  (* src = "mem512x32.sv:50.9-50.28" *)
  wire _16_;
  (* src = "mem512x32.sv:62.9-62.28" *)
  wire _17_;
  (* src = "mem512x32.sv:74.9-74.28" *)
  wire _18_;
  (* src = "mem512x32.sv:87.9-87.28" *)
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  (* src = "mem2048x32.sv:8.21-8.26" *)
  input clk_i;
  wire clk_i;
  (* src = "mem2048x32.sv:14.21-14.31" *)
  input [31:0] mem_addr_i;
  wire [31:0] mem_addr_i;
  (* src = "mem2048x32.sv:12.21-12.32" *)
  input [0:0] mem_instr_i;
  wire [0:0] mem_instr_i;
  (* src = "mem2048x32.sv:18.21-18.32" *)
  output [31:0] mem_rdata_o;
  wire [31:0] mem_rdata_o;
  (* src = "mem2048x32.sv:24.14-24.27" *)
  wire [31:0] mem_rdata_o_0;
  (* src = "mem2048x32.sv:24.29-24.42" *)
  wire [31:0] mem_rdata_o_1;
  (* src = "mem2048x32.sv:24.44-24.57" *)
  wire [31:0] mem_rdata_o_2;
  (* src = "mem2048x32.sv:24.59-24.72" *)
  wire [31:0] mem_rdata_o_3;
  (* src = "mem2048x32.sv:25.14-25.31" *)
  wire [31:0] mem_rdata_o_logic;
  (* src = "mem2048x32.sv:19.21-19.32" *)
  output [0:0] mem_ready_o;
  wire [0:0] mem_ready_o;
  (* src = "mem2048x32.sv:26.14-26.27" *)
  wire [0:0] mem_ready_o_0;
  (* src = "mem2048x32.sv:26.29-26.42" *)
  wire [0:0] mem_ready_o_1;
  (* src = "mem2048x32.sv:26.44-26.57" *)
  wire [0:0] mem_ready_o_2;
  (* src = "mem2048x32.sv:26.59-26.72" *)
  wire [0:0] mem_ready_o_3;
  (* src = "mem2048x32.sv:27.14-27.31" *)
  wire [0:0] mem_ready_o_logic;
  (* src = "mem2048x32.sv:11.21-11.32" *)
  input [0:0] mem_valid_i;
  wire [0:0] mem_valid_i;
  (* src = "mem2048x32.sv:30.14-30.27" *)
  wire [0:0] mem_valid_i_0;
  (* src = "mem2048x32.sv:30.29-30.42" *)
  wire [0:0] mem_valid_i_1;
  (* src = "mem2048x32.sv:30.44-30.57" *)
  wire [0:0] mem_valid_i_2;
  (* src = "mem2048x32.sv:30.59-30.72" *)
  wire [0:0] mem_valid_i_3;
  (* src = "mem2048x32.sv:15.21-15.32" *)
  input [31:0] mem_wdata_i;
  wire [31:0] mem_wdata_i;
  (* src = "mem2048x32.sv:16.21-16.32" *)
  input [3:0] mem_wstrb_i;
  wire [3:0] mem_wstrb_i;
  (* hdlname = "memblock0 clk_i" *)
  (* src = "mem512x32.sv:8.21-8.26" *)
  wire \memblock0.clk_i ;
  (* hdlname = "memblock0 data_read" *)
  (* src = "mem512x32.sv:27.14-27.23" *)
  wire [31:0] \memblock0.data_read ;
  (* hdlname = "memblock0 data_to_write" *)
  (* src = "mem512x32.sv:26.14-26.27" *)
  wire [31:0] \memblock0.data_to_write ;
  (* hdlname = "memblock0 mem_addr_i" *)
  (* src = "mem512x32.sv:14.21-14.31" *)
  (* unused_bits = "11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] \memblock0.mem_addr_i ;
  (* hdlname = "memblock0 mem_instr_i" *)
  (* src = "mem512x32.sv:12.21-12.32" *)
  (* unused_bits = "0" *)
  wire [0:0] \memblock0.mem_instr_i ;
  (* hdlname = "memblock0 mem_rdata_o" *)
  (* src = "mem512x32.sv:18.21-18.32" *)
  wire [31:0] \memblock0.mem_rdata_o ;
  (* hdlname = "memblock0 mem_ready_o" *)
  (* src = "mem512x32.sv:19.21-19.32" *)
  wire [0:0] \memblock0.mem_ready_o ;
  (* hdlname = "memblock0 mem_valid_i" *)
  (* src = "mem512x32.sv:11.21-11.32" *)
  wire [0:0] \memblock0.mem_valid_i ;
  (* hdlname = "memblock0 mem_wdata_i" *)
  (* src = "mem512x32.sv:15.21-15.32" *)
  wire [31:0] \memblock0.mem_wdata_i ;
  (* hdlname = "memblock0 mem_wstrb_i" *)
  (* src = "mem512x32.sv:16.21-16.32" *)
  wire [3:0] \memblock0.mem_wstrb_i ;
  (* hdlname = "memblock0 rst_ni" *)
  (* src = "mem512x32.sv:9.21-9.27" *)
  (* unused_bits = "0" *)
  wire \memblock0.rst_ni ;
  (* hdlname = "memblock0 sram_addr" *)
  (* src = "mem512x32.sv:25.13-25.22" *)
  wire [8:0] \memblock0.sram_addr ;
  (* hdlname = "memblock0 sram_enable_n" *)
  (* src = "mem512x32.sv:22.7-22.20" *)
  wire \memblock0.sram_enable_n ;
  (* hdlname = "memblock0 sram_write_bit_mask_n" *)
  (* src = "mem512x32.sv:24.13-24.34" *)
  wire [7:0] \memblock0.sram_write_bit_mask_n ;
  (* hdlname = "memblock0 sram_write_en_n" *)
  (* src = "mem512x32.sv:23.13-23.28" *)
  wire [3:0] \memblock0.sram_write_en_n ;
  (* hdlname = "memblock1 clk_i" *)
  (* src = "mem512x32.sv:8.21-8.26" *)
  wire \memblock1.clk_i ;
  (* hdlname = "memblock1 data_read" *)
  (* src = "mem512x32.sv:27.14-27.23" *)
  wire [31:0] \memblock1.data_read ;
  (* hdlname = "memblock1 data_to_write" *)
  (* src = "mem512x32.sv:26.14-26.27" *)
  wire [31:0] \memblock1.data_to_write ;
  (* hdlname = "memblock1 mem_addr_i" *)
  (* src = "mem512x32.sv:14.21-14.31" *)
  (* unused_bits = "11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] \memblock1.mem_addr_i ;
  (* hdlname = "memblock1 mem_instr_i" *)
  (* src = "mem512x32.sv:12.21-12.32" *)
  (* unused_bits = "0" *)
  wire [0:0] \memblock1.mem_instr_i ;
  (* hdlname = "memblock1 mem_rdata_o" *)
  (* src = "mem512x32.sv:18.21-18.32" *)
  wire [31:0] \memblock1.mem_rdata_o ;
  (* hdlname = "memblock1 mem_ready_o" *)
  (* src = "mem512x32.sv:19.21-19.32" *)
  wire [0:0] \memblock1.mem_ready_o ;
  (* hdlname = "memblock1 mem_valid_i" *)
  (* src = "mem512x32.sv:11.21-11.32" *)
  wire [0:0] \memblock1.mem_valid_i ;
  (* hdlname = "memblock1 mem_wdata_i" *)
  (* src = "mem512x32.sv:15.21-15.32" *)
  wire [31:0] \memblock1.mem_wdata_i ;
  (* hdlname = "memblock1 mem_wstrb_i" *)
  (* src = "mem512x32.sv:16.21-16.32" *)
  wire [3:0] \memblock1.mem_wstrb_i ;
  (* hdlname = "memblock1 rst_ni" *)
  (* src = "mem512x32.sv:9.21-9.27" *)
  (* unused_bits = "0" *)
  wire \memblock1.rst_ni ;
  (* hdlname = "memblock1 sram_addr" *)
  (* src = "mem512x32.sv:25.13-25.22" *)
  wire [8:0] \memblock1.sram_addr ;
  (* hdlname = "memblock1 sram_enable_n" *)
  (* src = "mem512x32.sv:22.7-22.20" *)
  wire \memblock1.sram_enable_n ;
  (* hdlname = "memblock1 sram_write_bit_mask_n" *)
  (* src = "mem512x32.sv:24.13-24.34" *)
  wire [7:0] \memblock1.sram_write_bit_mask_n ;
  (* hdlname = "memblock1 sram_write_en_n" *)
  (* src = "mem512x32.sv:23.13-23.28" *)
  wire [3:0] \memblock1.sram_write_en_n ;
  (* hdlname = "memblock2 clk_i" *)
  (* src = "mem512x32.sv:8.21-8.26" *)
  wire \memblock2.clk_i ;
  (* hdlname = "memblock2 data_read" *)
  (* src = "mem512x32.sv:27.14-27.23" *)
  wire [31:0] \memblock2.data_read ;
  (* hdlname = "memblock2 data_to_write" *)
  (* src = "mem512x32.sv:26.14-26.27" *)
  wire [31:0] \memblock2.data_to_write ;
  (* hdlname = "memblock2 mem_addr_i" *)
  (* src = "mem512x32.sv:14.21-14.31" *)
  (* unused_bits = "11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] \memblock2.mem_addr_i ;
  (* hdlname = "memblock2 mem_instr_i" *)
  (* src = "mem512x32.sv:12.21-12.32" *)
  (* unused_bits = "0" *)
  wire [0:0] \memblock2.mem_instr_i ;
  (* hdlname = "memblock2 mem_rdata_o" *)
  (* src = "mem512x32.sv:18.21-18.32" *)
  wire [31:0] \memblock2.mem_rdata_o ;
  (* hdlname = "memblock2 mem_ready_o" *)
  (* src = "mem512x32.sv:19.21-19.32" *)
  wire [0:0] \memblock2.mem_ready_o ;
  (* hdlname = "memblock2 mem_valid_i" *)
  (* src = "mem512x32.sv:11.21-11.32" *)
  wire [0:0] \memblock2.mem_valid_i ;
  (* hdlname = "memblock2 mem_wdata_i" *)
  (* src = "mem512x32.sv:15.21-15.32" *)
  wire [31:0] \memblock2.mem_wdata_i ;
  (* hdlname = "memblock2 mem_wstrb_i" *)
  (* src = "mem512x32.sv:16.21-16.32" *)
  wire [3:0] \memblock2.mem_wstrb_i ;
  (* hdlname = "memblock2 rst_ni" *)
  (* src = "mem512x32.sv:9.21-9.27" *)
  (* unused_bits = "0" *)
  wire \memblock2.rst_ni ;
  (* hdlname = "memblock2 sram_addr" *)
  (* src = "mem512x32.sv:25.13-25.22" *)
  wire [8:0] \memblock2.sram_addr ;
  (* hdlname = "memblock2 sram_enable_n" *)
  (* src = "mem512x32.sv:22.7-22.20" *)
  wire \memblock2.sram_enable_n ;
  (* hdlname = "memblock2 sram_write_bit_mask_n" *)
  (* src = "mem512x32.sv:24.13-24.34" *)
  wire [7:0] \memblock2.sram_write_bit_mask_n ;
  (* hdlname = "memblock2 sram_write_en_n" *)
  (* src = "mem512x32.sv:23.13-23.28" *)
  wire [3:0] \memblock2.sram_write_en_n ;
  (* hdlname = "memblock3 clk_i" *)
  (* src = "mem512x32.sv:8.21-8.26" *)
  wire \memblock3.clk_i ;
  (* hdlname = "memblock3 data_read" *)
  (* src = "mem512x32.sv:27.14-27.23" *)
  wire [31:0] \memblock3.data_read ;
  (* hdlname = "memblock3 data_to_write" *)
  (* src = "mem512x32.sv:26.14-26.27" *)
  wire [31:0] \memblock3.data_to_write ;
  (* hdlname = "memblock3 mem_addr_i" *)
  (* src = "mem512x32.sv:14.21-14.31" *)
  (* unused_bits = "11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] \memblock3.mem_addr_i ;
  (* hdlname = "memblock3 mem_instr_i" *)
  (* src = "mem512x32.sv:12.21-12.32" *)
  (* unused_bits = "0" *)
  wire [0:0] \memblock3.mem_instr_i ;
  (* hdlname = "memblock3 mem_rdata_o" *)
  (* src = "mem512x32.sv:18.21-18.32" *)
  wire [31:0] \memblock3.mem_rdata_o ;
  (* hdlname = "memblock3 mem_ready_o" *)
  (* src = "mem512x32.sv:19.21-19.32" *)
  wire [0:0] \memblock3.mem_ready_o ;
  (* hdlname = "memblock3 mem_valid_i" *)
  (* src = "mem512x32.sv:11.21-11.32" *)
  wire [0:0] \memblock3.mem_valid_i ;
  (* hdlname = "memblock3 mem_wdata_i" *)
  (* src = "mem512x32.sv:15.21-15.32" *)
  wire [31:0] \memblock3.mem_wdata_i ;
  (* hdlname = "memblock3 mem_wstrb_i" *)
  (* src = "mem512x32.sv:16.21-16.32" *)
  wire [3:0] \memblock3.mem_wstrb_i ;
  (* hdlname = "memblock3 rst_ni" *)
  (* src = "mem512x32.sv:9.21-9.27" *)
  (* unused_bits = "0" *)
  wire \memblock3.rst_ni ;
  (* hdlname = "memblock3 sram_addr" *)
  (* src = "mem512x32.sv:25.13-25.22" *)
  wire [8:0] \memblock3.sram_addr ;
  (* hdlname = "memblock3 sram_enable_n" *)
  (* src = "mem512x32.sv:22.7-22.20" *)
  wire \memblock3.sram_enable_n ;
  (* hdlname = "memblock3 sram_write_bit_mask_n" *)
  (* src = "mem512x32.sv:24.13-24.34" *)
  wire [7:0] \memblock3.sram_write_bit_mask_n ;
  (* hdlname = "memblock3 sram_write_en_n" *)
  (* src = "mem512x32.sv:23.13-23.28" *)
  wire [3:0] \memblock3.sram_write_en_n ;
  (* src = "mem2048x32.sv:9.21-9.27" *)
  input rst_ni;
  wire rst_ni;
  assign _00_ = | { _23_, _21_, _20_ };
  assign _01_ = | { _22_, _21_, _20_ };
  assign _02_ = | { _23_, _22_, _21_ };
  assign _03_ = | { _23_, _22_, _20_ };
  assign \memblock0.sram_enable_n  = ! (* src = "mem512x32.sv:33.25-33.37" *) mem_valid_i_0;
  assign _04_ = ~ (* src = "mem512x32.sv:50.9-50.28" *) mem_wstrb_i[0];
  assign _05_ = ~ (* src = "mem512x32.sv:62.9-62.28" *) mem_wstrb_i[1];
  assign _06_ = ~ (* src = "mem512x32.sv:74.9-74.28" *) mem_wstrb_i[2];
  assign _07_ = ~ (* src = "mem512x32.sv:87.9-87.28" *) mem_wstrb_i[3];
  assign \memblock1.sram_enable_n  = ! (* src = "mem512x32.sv:33.25-33.37" *) mem_valid_i_1;
  assign _08_ = ~ (* src = "mem512x32.sv:50.9-50.28" *) mem_wstrb_i[0];
  assign _09_ = ~ (* src = "mem512x32.sv:62.9-62.28" *) mem_wstrb_i[1];
  assign _10_ = ~ (* src = "mem512x32.sv:74.9-74.28" *) mem_wstrb_i[2];
  assign _11_ = ~ (* src = "mem512x32.sv:87.9-87.28" *) mem_wstrb_i[3];
  assign \memblock2.sram_enable_n  = ! (* src = "mem512x32.sv:33.25-33.37" *) mem_valid_i_2;
  assign _12_ = ~ (* src = "mem512x32.sv:50.9-50.28" *) mem_wstrb_i[0];
  assign _13_ = ~ (* src = "mem512x32.sv:62.9-62.28" *) mem_wstrb_i[1];
  assign _14_ = ~ (* src = "mem512x32.sv:74.9-74.28" *) mem_wstrb_i[2];
  assign _15_ = ~ (* src = "mem512x32.sv:87.9-87.28" *) mem_wstrb_i[3];
  assign \memblock3.sram_enable_n  = ! (* src = "mem512x32.sv:33.25-33.37" *) mem_valid_i_3;
  assign _16_ = ~ (* src = "mem512x32.sv:50.9-50.28" *) mem_wstrb_i[0];
  assign _17_ = ~ (* src = "mem512x32.sv:62.9-62.28" *) mem_wstrb_i[1];
  assign _18_ = ~ (* src = "mem512x32.sv:74.9-74.28" *) mem_wstrb_i[2];
  assign _19_ = ~ (* src = "mem512x32.sv:87.9-87.28" *) mem_wstrb_i[3];
  function [0:0] _48_;
    input [0:0] a;
    input [3:0] b;
    input [3:0] s;
    (* full_case = 32'd1 *)
    (* src = "mem2048x32.sv:0.0-0.0|mem2048x32.sv:42.2-66.9" *)
    (* parallel_case *)
    casez (s)
      4'b???1:
        _48_ = b[0:0];
      4'b??1?:
        _48_ = b[1:1];
      4'b?1??:
        _48_ = b[2:2];
      4'b1???:
        _48_ = b[3:3];
      default:
        _48_ = a;
    endcase
  endfunction
  assign mem_ready_o = _48_(1'hx, 4'hf, { _21_, _20_, _23_, _22_ });
  function [31:0] _49_;
    input [31:0] a;
    input [127:0] b;
    input [3:0] s;
    (* full_case = 32'd1 *)
    (* src = "mem2048x32.sv:0.0-0.0|mem2048x32.sv:42.2-66.9" *)
    (* parallel_case *)
    casez (s)
      4'b???1:
        _49_ = b[31:0];
      4'b??1?:
        _49_ = b[63:32];
      4'b?1??:
        _49_ = b[95:64];
      4'b1???:
        _49_ = b[127:96];
      default:
        _49_ = a;
    endcase
  endfunction
  assign mem_rdata_o = _49_(32'hxxxxxxxx, { mem_rdata_o_0, mem_rdata_o_1, mem_rdata_o_2, mem_rdata_o_3 }, { _21_, _20_, _23_, _22_ });
  function [0:0] _50_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "mem2048x32.sv:0.0-0.0|mem2048x32.sv:42.2-66.9" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _50_ = b[0:0];
      2'b1?:
        _50_ = b[1:1];
      default:
        _50_ = a;
    endcase
  endfunction
  assign mem_valid_i_3 = _50_(1'hx, { 1'h0, mem_valid_i }, { _00_, _22_ });
  function [0:0] _51_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "mem2048x32.sv:0.0-0.0|mem2048x32.sv:42.2-66.9" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _51_ = b[0:0];
      2'b1?:
        _51_ = b[1:1];
      default:
        _51_ = a;
    endcase
  endfunction
  assign mem_valid_i_2 = _51_(1'hx, { mem_valid_i, 1'h0 }, { _23_, _01_ });
  function [0:0] _52_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "mem2048x32.sv:0.0-0.0|mem2048x32.sv:42.2-66.9" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _52_ = b[0:0];
      2'b1?:
        _52_ = b[1:1];
      default:
        _52_ = a;
    endcase
  endfunction
  assign mem_valid_i_1 = _52_(1'hx, { mem_valid_i, 1'h0 }, { _20_, _02_ });
  assign _22_ = mem_addr_i[10:9] == (* full_case = 32'd1 *) (* src = "mem2048x32.sv:0.0-0.0|mem2048x32.sv:42.2-66.9" *) 2'h3;
  assign _23_ = mem_addr_i[10:9] == (* full_case = 32'd1 *) (* src = "mem2048x32.sv:0.0-0.0|mem2048x32.sv:42.2-66.9" *) 2'h2;
  assign _20_ = mem_addr_i[10:9] == (* full_case = 32'd1 *) (* src = "mem2048x32.sv:0.0-0.0|mem2048x32.sv:42.2-66.9" *) 2'h1;
  assign _21_ = ! (* full_case = 32'd1 *) (* src = "mem2048x32.sv:0.0-0.0|mem2048x32.sv:42.2-66.9" *) mem_addr_i[10:9];
  function [0:0] _57_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "mem2048x32.sv:0.0-0.0|mem2048x32.sv:42.2-66.9" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _57_ = b[0:0];
      2'b1?:
        _57_ = b[1:1];
      default:
        _57_ = a;
    endcase
  endfunction
  assign mem_valid_i_0 = _57_(1'hx, { mem_valid_i, 1'h0 }, { _21_, _03_ });
  (* hdlname = "memblock0 sram0" *)
  (* module_not_derived = 32'd1 *)
  (* src = "mem512x32.sv:47.38-57.3" *)
  gf180mcu_fd_ip_sram__sram512x8m8wm1 \memblock0.sram0  (
    .A(mem_addr_i[8:0]),
    .CEN(\memblock0.sram_enable_n ),
    .CLK(clk_i),
    .D(mem_wdata_i[7:0]),
    .GWEN(_04_),
    .Q(mem_rdata_o_0[7:0]),
    .WEN(8'h00)
  );
  (* hdlname = "memblock0 sram1" *)
  (* module_not_derived = 32'd1 *)
  (* src = "mem512x32.sv:59.38-69.3" *)
  gf180mcu_fd_ip_sram__sram512x8m8wm1 \memblock0.sram1  (
    .A(mem_addr_i[8:0]),
    .CEN(\memblock0.sram_enable_n ),
    .CLK(clk_i),
    .D(mem_wdata_i[15:8]),
    .GWEN(_05_),
    .Q(mem_rdata_o_0[15:8]),
    .WEN(8'h00)
  );
  (* hdlname = "memblock0 sram2" *)
  (* module_not_derived = 32'd1 *)
  (* src = "mem512x32.sv:71.38-81.3" *)
  gf180mcu_fd_ip_sram__sram512x8m8wm1 \memblock0.sram2  (
    .A(mem_addr_i[8:0]),
    .CEN(\memblock0.sram_enable_n ),
    .CLK(clk_i),
    .D(mem_wdata_i[23:16]),
    .GWEN(_06_),
    .Q(mem_rdata_o_0[23:16]),
    .WEN(8'h00)
  );
  (* hdlname = "memblock0 sram3" *)
  (* module_not_derived = 32'd1 *)
  (* src = "mem512x32.sv:84.38-94.3" *)
  gf180mcu_fd_ip_sram__sram512x8m8wm1 \memblock0.sram3  (
    .A(mem_addr_i[8:0]),
    .CEN(\memblock0.sram_enable_n ),
    .CLK(clk_i),
    .D(mem_wdata_i[31:24]),
    .GWEN(_07_),
    .Q(mem_rdata_o_0[31:24]),
    .WEN(8'h00)
  );
  (* hdlname = "memblock1 sram0" *)
  (* module_not_derived = 32'd1 *)
  (* src = "mem512x32.sv:47.38-57.3" *)
  gf180mcu_fd_ip_sram__sram512x8m8wm1 \memblock1.sram0  (
    .A(mem_addr_i[8:0]),
    .CEN(\memblock1.sram_enable_n ),
    .CLK(clk_i),
    .D(mem_wdata_i[7:0]),
    .GWEN(_08_),
    .Q(mem_rdata_o_1[7:0]),
    .WEN(8'h00)
  );
  (* hdlname = "memblock1 sram1" *)
  (* module_not_derived = 32'd1 *)
  (* src = "mem512x32.sv:59.38-69.3" *)
  gf180mcu_fd_ip_sram__sram512x8m8wm1 \memblock1.sram1  (
    .A(mem_addr_i[8:0]),
    .CEN(\memblock1.sram_enable_n ),
    .CLK(clk_i),
    .D(mem_wdata_i[15:8]),
    .GWEN(_09_),
    .Q(mem_rdata_o_1[15:8]),
    .WEN(8'h00)
  );
  (* hdlname = "memblock1 sram2" *)
  (* module_not_derived = 32'd1 *)
  (* src = "mem512x32.sv:71.38-81.3" *)
  gf180mcu_fd_ip_sram__sram512x8m8wm1 \memblock1.sram2  (
    .A(mem_addr_i[8:0]),
    .CEN(\memblock1.sram_enable_n ),
    .CLK(clk_i),
    .D(mem_wdata_i[23:16]),
    .GWEN(_10_),
    .Q(mem_rdata_o_1[23:16]),
    .WEN(8'h00)
  );
  (* hdlname = "memblock1 sram3" *)
  (* module_not_derived = 32'd1 *)
  (* src = "mem512x32.sv:84.38-94.3" *)
  gf180mcu_fd_ip_sram__sram512x8m8wm1 \memblock1.sram3  (
    .A(mem_addr_i[8:0]),
    .CEN(\memblock1.sram_enable_n ),
    .CLK(clk_i),
    .D(mem_wdata_i[31:24]),
    .GWEN(_11_),
    .Q(mem_rdata_o_1[31:24]),
    .WEN(8'h00)
  );
  (* hdlname = "memblock2 sram0" *)
  (* module_not_derived = 32'd1 *)
  (* src = "mem512x32.sv:47.38-57.3" *)
  gf180mcu_fd_ip_sram__sram512x8m8wm1 \memblock2.sram0  (
    .A(mem_addr_i[8:0]),
    .CEN(\memblock2.sram_enable_n ),
    .CLK(clk_i),
    .D(mem_wdata_i[7:0]),
    .GWEN(_12_),
    .Q(mem_rdata_o_2[7:0]),
    .WEN(8'h00)
  );
  (* hdlname = "memblock2 sram1" *)
  (* module_not_derived = 32'd1 *)
  (* src = "mem512x32.sv:59.38-69.3" *)
  gf180mcu_fd_ip_sram__sram512x8m8wm1 \memblock2.sram1  (
    .A(mem_addr_i[8:0]),
    .CEN(\memblock2.sram_enable_n ),
    .CLK(clk_i),
    .D(mem_wdata_i[15:8]),
    .GWEN(_13_),
    .Q(mem_rdata_o_2[15:8]),
    .WEN(8'h00)
  );
  (* hdlname = "memblock2 sram2" *)
  (* module_not_derived = 32'd1 *)
  (* src = "mem512x32.sv:71.38-81.3" *)
  gf180mcu_fd_ip_sram__sram512x8m8wm1 \memblock2.sram2  (
    .A(mem_addr_i[8:0]),
    .CEN(\memblock2.sram_enable_n ),
    .CLK(clk_i),
    .D(mem_wdata_i[23:16]),
    .GWEN(_14_),
    .Q(mem_rdata_o_2[23:16]),
    .WEN(8'h00)
  );
  (* hdlname = "memblock2 sram3" *)
  (* module_not_derived = 32'd1 *)
  (* src = "mem512x32.sv:84.38-94.3" *)
  gf180mcu_fd_ip_sram__sram512x8m8wm1 \memblock2.sram3  (
    .A(mem_addr_i[8:0]),
    .CEN(\memblock2.sram_enable_n ),
    .CLK(clk_i),
    .D(mem_wdata_i[31:24]),
    .GWEN(_15_),
    .Q(mem_rdata_o_2[31:24]),
    .WEN(8'h00)
  );
  (* hdlname = "memblock3 sram0" *)
  (* module_not_derived = 32'd1 *)
  (* src = "mem512x32.sv:47.38-57.3" *)
  gf180mcu_fd_ip_sram__sram512x8m8wm1 \memblock3.sram0  (
    .A(mem_addr_i[8:0]),
    .CEN(\memblock3.sram_enable_n ),
    .CLK(clk_i),
    .D(mem_wdata_i[7:0]),
    .GWEN(_16_),
    .Q(mem_rdata_o_3[7:0]),
    .WEN(8'h00)
  );
  (* hdlname = "memblock3 sram1" *)
  (* module_not_derived = 32'd1 *)
  (* src = "mem512x32.sv:59.38-69.3" *)
  gf180mcu_fd_ip_sram__sram512x8m8wm1 \memblock3.sram1  (
    .A(mem_addr_i[8:0]),
    .CEN(\memblock3.sram_enable_n ),
    .CLK(clk_i),
    .D(mem_wdata_i[15:8]),
    .GWEN(_17_),
    .Q(mem_rdata_o_3[15:8]),
    .WEN(8'h00)
  );
  (* hdlname = "memblock3 sram2" *)
  (* module_not_derived = 32'd1 *)
  (* src = "mem512x32.sv:71.38-81.3" *)
  gf180mcu_fd_ip_sram__sram512x8m8wm1 \memblock3.sram2  (
    .A(mem_addr_i[8:0]),
    .CEN(\memblock3.sram_enable_n ),
    .CLK(clk_i),
    .D(mem_wdata_i[23:16]),
    .GWEN(_18_),
    .Q(mem_rdata_o_3[23:16]),
    .WEN(8'h00)
  );
  (* hdlname = "memblock3 sram3" *)
  (* module_not_derived = 32'd1 *)
  (* src = "mem512x32.sv:84.38-94.3" *)
  gf180mcu_fd_ip_sram__sram512x8m8wm1 \memblock3.sram3  (
    .A(mem_addr_i[8:0]),
    .CEN(\memblock3.sram_enable_n ),
    .CLK(clk_i),
    .D(mem_wdata_i[31:24]),
    .GWEN(_19_),
    .Q(mem_rdata_o_3[31:24]),
    .WEN(8'h00)
  );
  assign \memblock0.sram_write_en_n  = mem_wstrb_i;
  assign \memblock0.sram_write_bit_mask_n  = 8'h00;
  assign \memblock0.sram_addr  = mem_addr_i[8:0];
  assign \memblock0.rst_ni  = rst_ni;
  assign \memblock0.mem_wstrb_i  = mem_wstrb_i;
  assign \memblock0.mem_wdata_i  = mem_wdata_i;
  assign \memblock0.mem_valid_i  = mem_valid_i_0;
  assign \memblock0.mem_ready_o  = 1'h1;
  assign \memblock0.mem_rdata_o  = mem_rdata_o_0;
  assign \memblock0.mem_instr_i  = mem_instr_i;
  assign \memblock0.mem_addr_i  = mem_addr_i;
  assign \memblock0.data_to_write  = mem_wdata_i;
  assign \memblock0.data_read  = mem_rdata_o_0;
  assign \memblock0.clk_i  = clk_i;
  assign \memblock1.sram_write_en_n  = mem_wstrb_i;
  assign \memblock1.sram_write_bit_mask_n  = 8'h00;
  assign \memblock1.sram_addr  = mem_addr_i[8:0];
  assign \memblock1.rst_ni  = rst_ni;
  assign \memblock1.mem_wstrb_i  = mem_wstrb_i;
  assign \memblock1.mem_wdata_i  = mem_wdata_i;
  assign \memblock1.mem_valid_i  = mem_valid_i_1;
  assign \memblock1.mem_ready_o  = 1'h1;
  assign \memblock1.mem_rdata_o  = mem_rdata_o_1;
  assign \memblock1.mem_instr_i  = mem_instr_i;
  assign \memblock1.mem_addr_i  = mem_addr_i;
  assign \memblock1.data_to_write  = mem_wdata_i;
  assign \memblock1.data_read  = mem_rdata_o_1;
  assign \memblock1.clk_i  = clk_i;
  assign \memblock2.sram_write_en_n  = mem_wstrb_i;
  assign \memblock2.sram_write_bit_mask_n  = 8'h00;
  assign \memblock2.sram_addr  = mem_addr_i[8:0];
  assign \memblock2.rst_ni  = rst_ni;
  assign \memblock2.mem_wstrb_i  = mem_wstrb_i;
  assign \memblock2.mem_wdata_i  = mem_wdata_i;
  assign \memblock2.mem_valid_i  = mem_valid_i_2;
  assign \memblock2.mem_ready_o  = 1'h1;
  assign \memblock2.mem_rdata_o  = mem_rdata_o_2;
  assign \memblock2.mem_instr_i  = mem_instr_i;
  assign \memblock2.mem_addr_i  = mem_addr_i;
  assign \memblock2.data_to_write  = mem_wdata_i;
  assign \memblock2.data_read  = mem_rdata_o_2;
  assign \memblock2.clk_i  = clk_i;
  assign \memblock3.sram_write_en_n  = mem_wstrb_i;
  assign \memblock3.sram_write_bit_mask_n  = 8'h00;
  assign \memblock3.sram_addr  = mem_addr_i[8:0];
  assign \memblock3.rst_ni  = rst_ni;
  assign \memblock3.mem_wstrb_i  = mem_wstrb_i;
  assign \memblock3.mem_wdata_i  = mem_wdata_i;
  assign \memblock3.mem_valid_i  = mem_valid_i_3;
  assign \memblock3.mem_ready_o  = 1'h1;
  assign \memblock3.mem_rdata_o  = mem_rdata_o_3;
  assign \memblock3.mem_instr_i  = mem_instr_i;
  assign \memblock3.mem_addr_i  = mem_addr_i;
  assign \memblock3.data_to_write  = mem_wdata_i;
  assign \memblock3.data_read  = mem_rdata_o_3;
  assign \memblock3.clk_i  = clk_i;
  assign mem_rdata_o_logic = mem_rdata_o;
  assign mem_ready_o_0 = 1'h1;
  assign mem_ready_o_1 = 1'h1;
  assign mem_ready_o_2 = 1'h1;
  assign mem_ready_o_3 = 1'h1;
  assign mem_ready_o_logic = mem_ready_o;
endmodule
